# Generated by Django 2.1.5 on 2019-01-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vokabel',
            old_name='deusch',
            new_name='deutsch',
        ),
    ]
